from setuptools import setup, find_namespace_packages

setup(name='unsupervised-metrics',
    version='1.0',
    description='Self-Learning for Unsupervised Metrics',
    keywords = ["Unsupervised", "Metrics", "Quality Estimation", "Machine Translation", "NLP", "Deep Learning"],
    url='https://github.com/potamides/unsupervised-metrics',
    author='Jonas Belouadi',
    author_email='potamides@posteo.net',
    packages=find_namespace_packages(include=["metrics*"]),
    install_requires=[
        "tqdm==4.49.0",
        "fasttext==0.9.2",
        "faiss-gpu==1.6.5",
        "pyemd==0.5.1",
        "torch==1.9.0",
        "sentence-transformers==1.2.0",
        "transformers==4.5.1",
        "datasets==1.6.1",
        "cupy-cuda100==8.5.0",
        "nltk>=3.4.5",
        "sentencepiece==0.1.95",
        "mosestokenizer==1.1.0",
        "jieba==0.42.1",
        "sinling==0.3.6",
        "Nepali_nlp @ https://github.com/potamides/Nepali_nlp/archive/d3d078ed50c8224f290d772f7b895354d0cb0266.zip",
        "simalign @ https://github.com/cisnlp/simalign/archive/refs/tags/v0.2.zip",
        "PuLP==2.4",
        "bert-score==0.3.9",
        "truecase==0.0.12",
        "tabulate==0.8.9"
    ],
    python_requires=">=3.9.0",
    zip_safe=False,
)
